# Generated by Django 5.0.3 on 2024-06-29 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_team_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='season',
            field=models.IntegerField(unique=True),
        ),
    ]
