# Generated by Django 5.0.3 on 2024-08-05 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0006_team_surge"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "playbook",
                    models.CharField(default="Team Playbook 1", max_length=32),
                ),
                (
                    "offensive_focus",
                    models.CharField(default="No Preference", max_length=32),
                ),
                (
                    "offensive_tempo",
                    models.CharField(default="No Preference", max_length=32),
                ),
                (
                    "offensive_rebounding",
                    models.CharField(default="No Preference", max_length=32),
                ),
                (
                    "defensive_focus",
                    models.CharField(default="No Preference", max_length=32),
                ),
                (
                    "defensive_aggression",
                    models.CharField(default="No Preference", max_length=32),
                ),
                (
                    "defensive_rebounding",
                    models.CharField(default="No Preference", max_length=32),
                ),
                ("run_plays", models.IntegerField(default=50)),
                ("zone_usage", models.IntegerField(default=50)),
                ("lineup", models.JSONField(default=dict)),
                ("initiators", models.JSONField(default=dict)),
                ("playtypes", models.JSONField(default=dict)),
                ("touches", models.JSONField(default=dict)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="teams.team"
                    ),
                ),
            ],
        ),
    ]
