# Generated by Django 5.0.3 on 2024-08-05 21:18

import simulation.scripts.default
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0007_teamlogs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teamlogs",
            name="initiators",
        ),
        migrations.RemoveField(
            model_name="teamlogs",
            name="playtypes",
        ),
        migrations.RemoveField(
            model_name="teamlogs",
            name="touches",
        ),
        migrations.AlterField(
            model_name="teamlogs",
            name="lineup",
            field=models.JSONField(default=simulation.scripts.default.default_lineup),
        ),
    ]
