# Generated by Django 5.0.3 on 2024-10-10 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("players", "0040_player_rookie"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("rookies_allowed", models.BooleanField(default=False)),
                ("free_agents_allowed", models.BooleanField(default=False)),
                ("active_players_allowed", models.BooleanField(default=False)),
                ("use_spent_limit", models.BooleanField(default=False)),
                ("spent_limit", models.IntegerField(default=0)),
                ("max_Entrees", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Entree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="players.player"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
            ],
        ),
    ]
