# Generated by Django 5.0.3 on 2024-10-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entree",
            options={"verbose_name": "Entry", "verbose_name_plural": "Entries"},
        ),
        migrations.RenameField(
            model_name="event",
            old_name="max_Entrees",
            new_name="max_entries",
        ),
    ]
