# Generated by Django 5.0.3 on 2024-07-03 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_game_season_game_week'),
        ('teams', '0005_alter_draft_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(default='Regular', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='surge_game',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamgamestats',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stats.game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamgamestats',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
            preserve_default=False,
        ),
    ]
