# Generated by Django 5.0.3 on 2024-07-04 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_game_game_type_game_surge_game_teamgamestats_game_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamgamestats',
            name='points',
        ),
        migrations.AddField(
            model_name='game',
            name='away_team_stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_stats', to='stats.teamgamestats'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team_stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_stats', to='stats.teamgamestats'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Regular Season', 'Regular Season'), ('Playoff Game', 'Playoff Game'), ('All-Star Game', 'All-Star Game'), ('Preseason Game', 'Preseason Game'), ('Olympic Game', 'Olympic Game'), ('Showcase Game', 'Showcase Game')], max_length=100),
        ),
    ]
