# Generated by Django 5.0.3 on 2024-07-04 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_remove_teamgamestats_points_game_away_team_stats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_team_stats',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_stats', to='stats.teamgamestats'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team_stats',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_stats', to='stats.teamgamestats'),
            preserve_default=False,
        ),
    ]
