# Generated by Django 5.0.3 on 2024-07-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_alter_game_away_team_stats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_team_player_stats',
            field=models.ManyToManyField(related_name='away_team_player_stats', to='stats.playergamestats'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team_player_stats',
            field=models.ManyToManyField(related_name='home_team_player_stats', to='stats.playergamestats'),
        ),
    ]
