# Generated by Django 5.0.3 on 2024-07-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_alter_game_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergamestats',
            name='defensive_rebounds',
            field=models.IntegerField(default=0, help_text='Automatically calculated field'),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='points',
            field=models.IntegerField(help_text='Automatically calculated field'),
        ),
    ]
