# Generated by Django 5.0.3 on 2024-07-08 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_alter_playergamestats_defensive_rebounds_and_more'),
        ('teams', '0005_alter_draft_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamestats',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
            preserve_default=False,
        ),
    ]
