# Generated by Django 5.0.3 on 2024-07-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0014_teamgamestats_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamgamestats",
            name="assist_percentage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="teamgamestats",
            name="block_percentage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="teamgamestats",
            name="defensive_rebound_percentage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="teamgamestats",
            name="effective_field_goal_percentage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="teamgamestats",
            name="game_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="teamgamestats",
            name="offensive_rebound_percentage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="teamgamestats",
            name="pace",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="teamgamestats",
            name="steal_percentage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="teamgamestats",
            name="true_shooting_percentage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="teamgamestats",
            name="turnover_percentage",
            field=models.FloatField(default=0.0),
        ),
    ]
