# Generated by Django 5.0.3 on 2024-07-16 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0016_remove_teamgamestats_assist_percentage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playergamestats",
            name="assist_percentage",
        ),
        migrations.RemoveField(
            model_name="playergamestats",
            name="block_percentage",
        ),
        migrations.RemoveField(
            model_name="playergamestats",
            name="defensive_rebound_percentage",
        ),
        migrations.RemoveField(
            model_name="playergamestats",
            name="offensive_rebound_percentage",
        ),
        migrations.RemoveField(
            model_name="playergamestats",
            name="pace",
        ),
        migrations.RemoveField(
            model_name="playergamestats",
            name="steal_percentage",
        ),
    ]
