# Generated by Django 5.0.3 on 2024-07-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0017_remove_playergamestats_assist_percentage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playergamestats",
            name="effective_field_goal_percentage",
            field=models.FloatField(
                default=0.0, help_text="Automatically calculated field"
            ),
        ),
        migrations.AlterField(
            model_name="playergamestats",
            name="game_score",
            field=models.FloatField(
                default=0.0, help_text="Automatically calculated field"
            ),
        ),
        migrations.AlterField(
            model_name="playergamestats",
            name="true_shooting_percentage",
            field=models.FloatField(
                default=0.0, help_text="Automatically calculated field"
            ),
        ),
        migrations.AlterField(
            model_name="playergamestats",
            name="turnover_percentage",
            field=models.FloatField(
                default=0.0, help_text="Automatically calculated field"
            ),
        ),
    ]
