# Generated by Django 5.0.3 on 2024-07-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0020_remove_season_end_date_remove_season_start_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="season",
            name="highest_assists",
            field=models.CharField(default="N/A", max_length=32),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_blocks",
            field=models.CharField(default="N/A", max_length=32),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_defensive_rebounds",
            field=models.CharField(default="N/A", max_length=32),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_dunks",
            field=models.CharField(default="N/A", max_length=32),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_effective_field_goal_percentage",
            field=models.CharField(default="N/A", max_length=32),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_field_goals_attempted",
            field=models.CharField(default="N/A", max_length=32),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_field_goals_made",
            field=models.CharField(default="N/A", max_length=32),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_free_throws_attempted",
            field=models.CharField(default="N/A", max_length=32),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_free_throws_made",
            field=models.CharField(default="N/A", max_length=32),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_game_score",
            field=models.CharField(default="N/A", max_length=32),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_offensive_rebounds",
            field=models.CharField(default="N/A", max_length=32),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_personal_fouls",
            field=models.CharField(default="N/A", max_length=32),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_plus_minus",
            field=models.CharField(default="N/A", max_length=32),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_points",
            field=models.CharField(default="N/A", max_length=32),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_points_responsible_for",
            field=models.CharField(default="N/A", max_length=32),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_rebounds",
            field=models.CharField(default="N/A", max_length=32),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_steals",
            field=models.CharField(default="N/A", max_length=32),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_three_pointers_attempted",
            field=models.CharField(default="N/A", max_length=32),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_three_pointers_made",
            field=models.CharField(default="N/A", max_length=32),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_true_shooting_percentage",
            field=models.CharField(default="N/A", max_length=32),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_turnover_percentage",
            field=models.CharField(default="N/A", max_length=32),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_turnovers",
            field=models.CharField(default="N/A", max_length=32),
        ),
    ]
