# Generated by Django 5.0.3 on 2024-07-19 00:01

import stats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0022_alter_season_highest_assists_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="season",
            name="highest_assists",
            field=models.JSONField(
                blank=True, default=stats.models.default_game_highs, null=True
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_blocks",
            field=models.JSONField(
                blank=True, default=stats.models.default_game_highs, null=True
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_defensive_rebounds",
            field=models.JSONField(
                blank=True, default=stats.models.default_game_highs, null=True
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_dunks",
            field=models.JSONField(
                blank=True, default=stats.models.default_game_highs, null=True
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_effective_field_goal_percentage",
            field=models.JSONField(
                blank=True, default=stats.models.default_game_highs, null=True
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_field_goals_attempted",
            field=models.JSONField(
                blank=True, default=stats.models.default_game_highs, null=True
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_field_goals_made",
            field=models.JSONField(
                blank=True, default=stats.models.default_game_highs, null=True
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_free_throws_attempted",
            field=models.JSONField(
                blank=True, default=stats.models.default_game_highs, null=True
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_free_throws_made",
            field=models.JSONField(
                blank=True, default=stats.models.default_game_highs, null=True
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_game_score",
            field=models.JSONField(
                blank=True, default=stats.models.default_game_highs, null=True
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_offensive_rebounds",
            field=models.JSONField(
                blank=True, default=stats.models.default_game_highs, null=True
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_personal_fouls",
            field=models.JSONField(
                blank=True, default=stats.models.default_game_highs, null=True
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_plus_minus",
            field=models.JSONField(
                blank=True, default=stats.models.default_game_highs, null=True
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_points",
            field=models.JSONField(
                blank=True, default=stats.models.default_game_highs, null=True
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_points_responsible_for",
            field=models.JSONField(
                blank=True, default=stats.models.default_game_highs, null=True
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_rebounds",
            field=models.JSONField(
                blank=True, default=stats.models.default_game_highs, null=True
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_steals",
            field=models.JSONField(
                blank=True, default=stats.models.default_game_highs, null=True
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_three_pointers_attempted",
            field=models.JSONField(
                blank=True, default=stats.models.default_game_highs, null=True
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_three_pointers_made",
            field=models.JSONField(
                blank=True, default=stats.models.default_game_highs, null=True
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_true_shooting_percentage",
            field=models.JSONField(
                blank=True, default=stats.models.default_game_highs, null=True
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_turnover_percentage",
            field=models.JSONField(
                blank=True, default=stats.models.default_game_highs, null=True
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="highest_turnovers",
            field=models.JSONField(
                blank=True, default=stats.models.default_game_highs, null=True
            ),
        ),
    ]
