# Generated by Django 5.0.3 on 2024-07-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0023_alter_season_highest_assists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='current_storylines',
            field=models.TextField(blank=True, default='There are no current storylines', null=True),
        ),
    ]
