# Generated by Django 5.0.3 on 2024-07-30 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0025_remove_game_game_type_playoffseries_playoffgame"),
    ]

    operations = [
        migrations.CreateModel(
            name="Playoff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stats.season"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayoffRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Quarterfinals", "Quarterfinals"),
                            ("Semifinals", "Semifinals"),
                            ("Finals", "Finals"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "playoff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stats.playoff"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="playoff",
            name="round_1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="round_1",
                to="stats.playoffround",
            ),
        ),
        migrations.AddField(
            model_name="playoff",
            name="round_2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="round_2",
                to="stats.playoffround",
            ),
        ),
        migrations.AddField(
            model_name="playoff",
            name="round_3",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="round_3",
                to="stats.playoffround",
            ),
        ),
        migrations.AlterField(
            model_name="playoffseries",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stats.playoffround"
            ),
        ),
    ]
