# Generated by Django 5.0.3 on 2024-07-30 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0026_playoff_playoffround_playoff_round_1_playoff_round_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playoffseries",
            name="round",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stats.playoffround",
            ),
        ),
    ]
