# Generated by Django 5.0.3 on 2024-07-30 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0028_alter_playoffseries_round"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playoff",
            name="round_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="round_1",
                to="stats.playoffround",
            ),
        ),
        migrations.AlterField(
            model_name="playoff",
            name="round_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="round_2",
                to="stats.playoffround",
            ),
        ),
        migrations.AlterField(
            model_name="playoff",
            name="round_3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="round_3",
                to="stats.playoffround",
            ),
        ),
    ]
