# Generated by Django 5.0.3 on 2024-07-30 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0029_alter_playoff_round_1_alter_playoff_round_2_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playoff",
            old_name="round_3",
            new_name="finals",
        ),
        migrations.RenameField(
            model_name="playoff",
            old_name="round_2",
            new_name="semifinals",
        ),
        migrations.RemoveField(
            model_name="playoff",
            name="round_1",
        ),
        migrations.AddField(
            model_name="playoff",
            name="quarterfinals",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="round_1",
                to="stats.playoffround",
            ),
        ),
    ]
