# Generated by Django 5.0.3 on 2024-07-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0031_alter_playoff_finals_alter_playoff_quarterfinals_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playoffseries",
            name="wins_to_advance",
        ),
        migrations.AddField(
            model_name="playoffround",
            name="wins_to_advance",
            field=models.IntegerField(default=5),
        ),
    ]
