# Generated by Django 5.0.3 on 2024-08-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0035_alter_playerseasonstats_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerseasonstats",
            name="average_field_goal_percentage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="playerseasonstats",
            name="average_free_throw_percentage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="playerseasonstats",
            name="average_three_point_percentage",
            field=models.FloatField(default=0.0),
        ),
    ]
