# Generated by Django 5.0.3 on 2024-08-26 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0036_playerseasonstats_average_field_goal_percentage_and_more"),
        ("teams", "0008_remove_teamlogs_initiators_remove_teamlogs_playtypes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamSeasonStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("games_played", models.IntegerField(default=0)),
                ("wins", models.IntegerField(default=0)),
                ("losses", models.IntegerField(default=0)),
                ("points", models.IntegerField(default=0)),
                ("rebounds", models.IntegerField(default=0)),
                ("assists", models.IntegerField(default=0)),
                ("steals", models.IntegerField(default=0)),
                ("blocks", models.IntegerField(default=0)),
                ("turnovers", models.IntegerField(default=0)),
                ("field_goals_made", models.IntegerField(default=0)),
                ("field_goals_attempted", models.IntegerField(default=0)),
                ("three_pointers_made", models.IntegerField(default=0)),
                ("three_pointers_attempted", models.IntegerField(default=0)),
                ("free_throws_made", models.IntegerField(default=0)),
                ("free_throws_attempted", models.IntegerField(default=0)),
                ("offensive_rebounds", models.IntegerField(default=0)),
                ("personal_fouls", models.IntegerField(default=0)),
                ("plus_minus", models.IntegerField(default=0)),
                ("points_off_turnovers", models.IntegerField(default=0)),
                ("dunks", models.IntegerField(default=0)),
                ("biggest_lead", models.IntegerField(default=0)),
                ("average_points", models.FloatField(default=0.0)),
                ("average_rebounds", models.FloatField(default=0.0)),
                ("average_assists", models.FloatField(default=0.0)),
                ("average_steals", models.FloatField(default=0.0)),
                ("average_blocks", models.FloatField(default=0.0)),
                ("average_turnovers", models.FloatField(default=0.0)),
                ("average_field_goals_made", models.FloatField(default=0.0)),
                ("average_field_goals_attempted", models.FloatField(default=0.0)),
                ("average_field_goal_percentage", models.FloatField(default=0.0)),
                ("average_three_pointers_made", models.FloatField(default=0.0)),
                ("average_three_pointers_attempted", models.FloatField(default=0.0)),
                ("average_three_point_percentage", models.FloatField(default=0.0)),
                ("average_free_throws_made", models.FloatField(default=0.0)),
                ("average_free_throws_attempted", models.FloatField(default=0.0)),
                ("average_free_throw_percentage", models.FloatField(default=0.0)),
                ("average_offensive_rebounds", models.FloatField(default=0.0)),
                ("average_personal_fouls", models.FloatField(default=0.0)),
                ("average_plus_minus", models.FloatField(default=0.0)),
                ("average_points_off_turnovers", models.FloatField(default=0.0)),
                ("average_dunks", models.FloatField(default=0.0)),
                ("average_biggest_lead", models.FloatField(default=0.0)),
                ("game_high_points", models.IntegerField(default=0)),
                ("game_high_rebounds", models.IntegerField(default=0)),
                ("game_high_assists", models.IntegerField(default=0)),
                ("game_high_steals", models.IntegerField(default=0)),
                ("game_high_blocks", models.IntegerField(default=0)),
                ("game_high_turnovers", models.IntegerField(default=0)),
                ("game_high_field_goals_made", models.IntegerField(default=0)),
                ("game_high_field_goals_attempted", models.IntegerField(default=0)),
                ("game_high_three_pointers_made", models.IntegerField(default=0)),
                ("game_high_three_pointers_attempted", models.IntegerField(default=0)),
                ("game_high_free_throws_made", models.IntegerField(default=0)),
                ("game_high_free_throws_attempted", models.IntegerField(default=0)),
                ("game_high_offensive_rebounds", models.IntegerField(default=0)),
                ("game_high_personal_fouls", models.IntegerField(default=0)),
                ("game_high_plus_minus", models.IntegerField(default=0)),
                ("game_high_points_off_turnovers", models.IntegerField(default=0)),
                ("game_high_dunks", models.IntegerField(default=0)),
                ("game_high_biggest_lead", models.IntegerField(default=0)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stats.season"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="teams.team"
                    ),
                ),
            ],
        ),
    ]
