# Generated by Django 5.0.3 on 2024-08-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0037_teamseasonstats"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teamseasonstats",
            options={"verbose_name_plural": "Team season stats"},
        ),
        migrations.AddField(
            model_name="teamseasonstats",
            name="average_defensive_rebounds",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="teamseasonstats",
            name="average_points_in_paint",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="teamseasonstats",
            name="average_second_chance_points",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="teamseasonstats",
            name="defensive_rebounds",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamseasonstats",
            name="game_high_defensive_rebounds",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamseasonstats",
            name="game_high_points_in_paint",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamseasonstats",
            name="game_high_second_chance_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamseasonstats",
            name="points_in_paint",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teamseasonstats",
            name="second_chance_points",
            field=models.IntegerField(default=0),
        ),
    ]
