# Generated by Django 5.0.3 on 2024-08-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0038_alter_teamseasonstats_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamseasonstats",
            name="point_differential",
            field=models.IntegerField(default=0),
        ),
    ]
