# Generated by Django 5.0.3 on 2024-08-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0040_teamgamestats_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamgamestats",
            name="point_differential",
            field=models.IntegerField(default=0),
        ),
    ]
