# Generated by Django 5.0.3 on 2024-08-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0041_teamgamestats_point_differential"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamseasonstats",
            name="average_point_differential",
            field=models.FloatField(default=0.0),
        ),
    ]
