# Generated by Django 5.0.3 on 2024-08-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0042_teamseasonstats_average_point_differential"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamgamestats",
            name="rebounds",
            field=models.IntegerField(
                default=0, help_text="Automatically calculated field"
            ),
        ),
    ]
