# Generated by Django 5.0.3 on 2024-08-26 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0043_teamgamestats_rebounds"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teamseasonstats",
            name="average_plus_minus",
        ),
        migrations.RemoveField(
            model_name="teamseasonstats",
            name="game_high_plus_minus",
        ),
        migrations.RemoveField(
            model_name="teamseasonstats",
            name="plus_minus",
        ),
    ]
