# Generated by Django 5.0.3 on 2024-08-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0045_game_player_game_stats_game_team_game_stats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="player_game_stats",
            field=models.ManyToManyField(
                blank=True, related_name="player_game_stats", to="stats.playergamestats"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="team_game_stats",
            field=models.ManyToManyField(
                blank=True, related_name="team_game_stats", to="stats.teamgamestats"
            ),
        ),
    ]
