# Generated by Django 5.0.3 on 2024-12-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0047_remove_game_player_game_stats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamgamestats',
            name='assists',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamgamestats',
            name='biggest_lead',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamgamestats',
            name='blocks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamgamestats',
            name='defensive_rebounds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamgamestats',
            name='dunks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamgamestats',
            name='fast_break_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamgamestats',
            name='field_goals_attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamgamestats',
            name='field_goals_made',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamgamestats',
            name='free_throws_attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamgamestats',
            name='free_throws_made',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamgamestats',
            name='offensive_rebounds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamgamestats',
            name='personal_fouls',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamgamestats',
            name='points_in_paint',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamgamestats',
            name='points_off_turnovers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamgamestats',
            name='second_chance_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamgamestats',
            name='steals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamgamestats',
            name='three_pointers_attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamgamestats',
            name='three_pointers_made',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamgamestats',
            name='time_of_possession',
            field=models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name='teamgamestats',
            name='turnovers',
            field=models.IntegerField(default=0),
        ),
    ]
