# Generated by Django 5.0.3 on 2024-12-11 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0048_alter_teamgamestats_assists_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamgamestats',
            name='bench_points',
        ),
        migrations.RemoveField(
            model_name='teamgamestats',
            name='biggest_lead',
        ),
        migrations.RemoveField(
            model_name='teamgamestats',
            name='fast_break_points',
        ),
        migrations.RemoveField(
            model_name='teamgamestats',
            name='points_in_paint',
        ),
        migrations.RemoveField(
            model_name='teamgamestats',
            name='points_off_turnovers',
        ),
        migrations.RemoveField(
            model_name='teamgamestats',
            name='second_chance_points',
        ),
        migrations.RemoveField(
            model_name='teamgamestats',
            name='time_of_possession',
        ),
    ]
