# Generated by Django 5.0.3 on 2024-12-11 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0049_remove_teamgamestats_bench_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamseasonstats',
            name='average_biggest_lead',
        ),
        migrations.RemoveField(
            model_name='teamseasonstats',
            name='average_points_in_paint',
        ),
        migrations.RemoveField(
            model_name='teamseasonstats',
            name='average_points_off_turnovers',
        ),
        migrations.RemoveField(
            model_name='teamseasonstats',
            name='average_second_chance_points',
        ),
        migrations.RemoveField(
            model_name='teamseasonstats',
            name='biggest_lead',
        ),
        migrations.RemoveField(
            model_name='teamseasonstats',
            name='game_high_biggest_lead',
        ),
        migrations.RemoveField(
            model_name='teamseasonstats',
            name='game_high_points_in_paint',
        ),
        migrations.RemoveField(
            model_name='teamseasonstats',
            name='game_high_points_off_turnovers',
        ),
        migrations.RemoveField(
            model_name='teamseasonstats',
            name='game_high_second_chance_points',
        ),
        migrations.RemoveField(
            model_name='teamseasonstats',
            name='points_in_paint',
        ),
        migrations.RemoveField(
            model_name='teamseasonstats',
            name='points_off_turnovers',
        ),
        migrations.RemoveField(
            model_name='teamseasonstats',
            name='second_chance_points',
        ),
    ]
