from simulation.sync import shared_lists, conversion_list

# Accessory options for players
accessory_options = {
    "Headband": conversion_list["Headband"],
    "Headband Logo": conversion_list["Headband Logo"],
    "Headband Frequency": conversion_list["Headband Frequency"],
    "Left Arm": conversion_list["Left Arm"],
    "Left Arm Frequency": conversion_list["Left Arm Frequency"],
    "Left Arm Home Color": conversion_list["Left Arm Home Color"],
    "Left Arm Away Color": conversion_list["Left Arm Away Color"],
    "Left Elbow": conversion_list["Left Elbow"],
    "Left Elbow Frequency": conversion_list["Left Elbow Frequency"],
    "Left Elbow Home Color": conversion_list["Left Elbow Home Color"],
    "Left Elbow Away Color": conversion_list["Left Elbow Away Color"],
    "Left Wrist": conversion_list["Left Wrist"],
    "Left Wrist Frequency": conversion_list["Left Wrist Frequency"],
    "Left Wrist Home Color": conversion_list["Left Wrist Home Color"],
    "Left Wrist Away Color": conversion_list["Left Wrist Away Color"],
    "Left Fingers": conversion_list["Left Fingers"],
    "Left Fingers Frequency": conversion_list["Left Fingers Frequency"],
    "Left Fingers Home Color": conversion_list["Left Fingers Home Color"],
    "Left Fingers Away Color": conversion_list["Left Fingers Away Color"],
    "Right Arm": conversion_list["Right Arm"],
    "Right Arm Frequency": conversion_list["Right Arm Frequency"],
    "Right Arm Home Color": conversion_list["Right Arm Home Color"],
    "Right Arm Away Color": conversion_list["Right Arm Away Color"],
    "Right Elbow": conversion_list["Right Elbow"],
    "Right Elbow Frequency": conversion_list["Right Elbow Frequency"],
    "Right Elbow Home Color": conversion_list["Right Elbow Home Color"],
    "Right Elbow Away Color": conversion_list["Right Elbow Away Color"],
    "Right Wrist": conversion_list["Right Wrist"],
    "Right Wrist Frequency": conversion_list["Right Wrist Frequency"],
    "Right Wrist Home Color": conversion_list["Right Wrist Home Color"],
    "Right Wrist Away Color": conversion_list["Right Wrist Away Color"],
    "Right Fingers": conversion_list["Right Fingers"],
    "Right Fingers Frequency": conversion_list["Right Fingers Frequency"],
    "Right Fingers Home Color": conversion_list["Right Fingers Home Color"],
    "Right Fingers Away Color": conversion_list["Right Fingers Away Color"],
    "Arm Frequency Paired": conversion_list["Arm Frequency Paired"],
}