from simulation.sync import shared_lists, conversion_list

# Accessory options for players
accessory_options = {
    "Headband": conversion_list["Headband"],
    "Headband Logo": conversion_list["Headband Logo"],
    "Headband Frequency": conversion_list["Headband Frequency"],
    "Left Arm": conversion_list["Left Arm"],
    "Left Arm Frequency": conversion_list["Left Arm Frequency"],
    "Left Arm Home Color": conversion_list["Left Arm Home Color"],
    "Left Arm Away Color": conversion_list["Left Arm Away Color"],
    "Left Elbow": conversion_list["Left Elbow"],
    "Left Elbow Frequency": conversion_list["Left Elbow Frequency"],
    "Left Elbow Home Color": conversion_list["Left Elbow Home Color"],
    "Left Elbow Away Color": conversion_list["Left Elbow Away Color"],
    "Left Wrist": conversion_list["Left Wrist"],
    "Left Wrist Frequency": conversion_list["Left Wrist Frequency"],
    "Left Wrist Home Color": conversion_list["Left Wrist Home Color"],
    "Left Wrist Away Color": conversion_list["Left Wrist Away Color"],
    "Left Fingers": conversion_list["Left Fingers"],
    "Left Fingers Frequency": conversion_list["Left Fingers Frequency"],
    "Left Fingers Home Color": conversion_list["Left Fingers Home Color"],
    "Left Fingers Away Color": conversion_list["Left Fingers Away Color"],
    "Right Arm": conversion_list["Right Arm"],
    "Right Arm Frequency": conversion_list["Right Arm Frequency"],
    "Right Arm Home Color": conversion_list["Right Arm Home Color"],
    "Right Arm Away Color": conversion_list["Right Arm Away Color"],
    "Right Elbow": conversion_list["Right Elbow"],
    "Right Elbow Frequency": conversion_list["Right Elbow Frequency"],
    "Right Elbow Home Color": conversion_list["Right Elbow Home Color"],
    "Right Elbow Away Color": conversion_list["Right Elbow Away Color"],
    "Right Wrist": conversion_list["Right Wrist"],
    "Right Wrist Frequency": conversion_list["Right Wrist Frequency"],
    "Right Wrist Home Color": conversion_list["Right Wrist Home Color"],
    "Right Wrist Away Color": conversion_list["Right Wrist Away Color"],
    "Right Fingers": conversion_list["Right Fingers"],
    "Right Fingers Frequency": conversion_list["Right Fingers Frequency"],
    "Right Fingers Home Color": conversion_list["Right Fingers Home Color"],
    "Right Fingers Away Color": conversion_list["Right Fingers Away Color"],
    "Arm Frequency Paired": conversion_list["Arm Frequency Paired"],
    "Left Leg": conversion_list["Left Leg"],
    "Left Leg Frequency": conversion_list["Left Leg Frequency"],
    "Left Leg Home Color": conversion_list["Left Leg Home Color"],
    "Left Leg Away Color": conversion_list["Left Leg Away Color"],
    "Left Knee": conversion_list["Left Knee"],
    "Left Knee Frequency": conversion_list["Left Knee Frequency"],
    "Left Knee Home Color": conversion_list["Left Knee Home Color"],
    "Left Knee Away Color": conversion_list["Left Knee Away Color"],
    "Left Ankle": conversion_list["Left Ankle"],
    "Left Ankle Frequency": conversion_list["Left Ankle Frequency"],
    "Left Ankle Home Color": conversion_list["Left Ankle Home Color"],
    "Left Ankle Away Color": conversion_list["Left Ankle Away Color"],
    "Right Leg": conversion_list["Right Leg"],
    "Right Leg Frequency": conversion_list["Right Leg Frequency"],
    "Right Leg Home Color": conversion_list["Right Leg Home Color"],
    "Right Leg Away Color": conversion_list["Right Leg Away Color"],
    "Right Knee": conversion_list["Right Knee"],
    "Right Knee Frequency": conversion_list["Right Knee Frequency"],
    "Right Knee Home Color": conversion_list["Right Knee Home Color"],
    "Right Knee Away Color": conversion_list["Right Knee Away Color"],
    "Right Ankle": conversion_list["Right Ankle"],
    "Right Ankle Frequency": conversion_list["Right Ankle Frequency"],
    "Right Ankle Home Color": conversion_list["Right Ankle Home Color"],
    "Right Ankle Away Color": conversion_list["Right Ankle Away Color"],
    "Leg Frequency Paired": conversion_list["Leg Frequency Paired"],
    "Knee Frequency Paired": conversion_list["Knee Frequency Paired"],
}