# Python imports
import random

# Local imports
from simulation.scripts.utility import real_range

# Jumpshot list
jumpshot_list = {
    real_range(72, 77): [
    "Nickeil Alexander-Walker",
    "Grayson Allen",
    "Jose Alvarado",
    "Cole Anthony",
    "Ryan Arcidiacono",
    "DJ Augustin",
    "LaMelo Ball",
    "Lonzo Ball",
    "Dalano Banton",
    "Dick Barnett",
    "Kent Bazemore",
    "Bradley Beal",
    "Malik Beasley",
    "Patrick Beverley",
    "Chauncey Billups",
    "Eric Bledsoe",
    "Devin Booker",
    "James Bouknight",
    "Malcolm Brogdon",
    "Bruce Brown",
    "Kobe Bufkin",
    "Jared Butler",
    "Facundo Campazzo",
    "Carlton Carrington",
    "Devin Carter",
    "Jevon Carter",
    "Michael Carter-Williams",
    "Alex Caruso",
    "Josh Christopher",
    "Jordan Clarkson",
    "Nicolas Claxton",
    "Isaiah Collier",
    "Darren Collison",
    "Mike Conley",
    "Seth Curry",
    "Stephen Curry",
    "Johnny Davis",
    "Terence Davis",
    "Matthew Dellavedova",
    "Robert Dillingham",
    "Spencer Dinwiddie",
    "Donte DiVincenzo",
    "Luka Doncic",
    "Luguentz Dort",
    "Ayo Dosunmu",
    "Goran Dragic",
    "Kris Dunn",
    "Anthony Edwards",
    "Keon Ellis",
    "Derek Fisher",
    "Malachi Flynn",
    "Bryn Forbes",
    "De'Aaron Fox",
    "Steve Francis",
    "Markelle Fultz",
    "Darius Garland",
    "Keyonte George",
    "Jordan Goodwin",
    "Eric Gordon",
    "Devonte' Graham",
    "A.J. Green",
    "Jalen Green",
    "Quentin Grimes",
    "Tyrese Haliburton",
    "R.J. Hampton",
    "Penny Hardaway",
    "James Harden",
    "Jaden Hardy",
    "Gary Harris",
    "Josh Hart",
    "Jordan Hawkins",
    "Killian Hayes",
    "Scoot Henderson",
    "Tyler Herro",
    "Buddy Hield",
    "Haywood Highsmith",
    "George Hill",
    "Aaron Holiday",
    "Jrue Holiday",
    "Talen Horton-Tucker",
    "Nah'Shon Hyland",
    "Kyrie Irving",
    "Allen Iverson",
    "Jaden Ivey",
    "Frank Jackson",
    "Reggie Jackson",
    "Bronny James Jr.",
    "Ty Jerome",
    "Isaiah Joe",
    "Keon Johnson",
    "Mason Jones",
    "Tre Jones",
    "Tyus Jones",
    "Cory Joseph",
    "Steve Kerr",
    "Jason Kidd",
    "Tyler Kolek",
    "Zach LaVine",
    "Damion Lee",
    "Saben Lee",
    "Kira Lewis Jr.",
    "Damian Lillard",
    "Kyle Lowry",
    "Theo Maledon",
    "Terance Mann",
    "Tre Mann",
    "Wesley Matthews",
    "Tyrese Maxey",
    "Skylar Mays",
    "Miles McBride",
    "Jared McCain",
    "CJ McCollum",
    "TJ McConnell",
    "Rodney McGruder",
    "Jordan McLaughlin",
    "De'Anthony Melton",
    "Sam Merrill",
    "Shake Milton",
    "Ajay Mitchell",
    "Davion Mitchell",
    "Donovan Mitchell",
    "Jonathan Mogbo",
    "Malik Monk",
    "Ja Morant",
    "Monte Morris",
    "Dejounte Murray",
    "Steve Nash",
    "Andrew Nembhard",
    "Raul Neto",
    "Daishen Nix",
    "Jaylen Nowell",
    "Frank Ntilikina",
    "Kendrick Nunn",
    "Josh Okogie",
    "Onyeka Okongwu",
    "Victor Oladipo",
    "Tony Parker",
    "Chris Paul",
    "Cameron Payne",
    "Elfrid Payton",
    "Gary Payton II",
    "Scotty Pippen Jr.",
    "Brandin Podziemski",
    "Jordan Poole",
    "Michael Porter Jr.",
    "Norman Powell",
    "Jason Preston",
    "Joshua Primo",
    "Payton Pritchard",
    "Trevelin Queen",
    "Immanuel Quickley",
    "Jahmi'us Ramsey",
    "Austin Reaves",
    "JJ Redick",
    "Austin Rivers",
    "Oscar Robertson",
    "Jerome Robinson",
    "Nate Robinson",
    "Rajon Rondo",
    "Derrick Rose",
    "Terry Rozier III",
    "Ricky Rubio",
    "D'Angelo Russell",
    "Marcus Sasser",
    "Dennis Schroder",
    "Collin Sexton",
    "Landry Shamet",
    "Reed Sheppard",
    "Anfernee Simons",
    "KJ Simpson",
    "Marcus Smart",
    "Dennis Smith Jr.",
    "Ish Smith",
    "Nick Smith Jr.",
    "Cam Spencer",
    "Jaden Springer",
    "John Stockton",
    "Jalen Suggs",
    "Edmond Sumner",
    "Jae'Sean Tate",
    "Cameron Thomas",
    "Isaiah Thomas",
    "Fred VanVleet",
    "Gabe Vincent",
    "Dwyane Wade",
    "Kemba Walker",
    "Lonnie Walker IV",
    "Cason Wallace",
    "Jakobe Walter",
    "TyTy Washington Jr.",
    "Quinndary Weatherspoon",
    "Chris Webber",
    "Blake Wesley",
    "Jerry West",
    "Russell Westbrook",
    "Coby White",
    "Derrick White",
    "Alondes Williams",
    "Jason Williams",
    "Louis Williams",
    "Mark Williams",
    "Vince Williams",
    "Delon Wright",
    "Trae Young",
    "Beluba",
    "Chris Brickley",
    "J. Cole",
    "LD2K",
    "Ronnie 2K",
    "Dan Rue",
    "L. Shooter"
],
    real_range(77, 81): [
    "Nickeil Alexander-Walker",
    "LaMelo Ball",
    "Lonzo Ball",
    "Dalano Banton",
    "Devin Booker",
    "Malcolm Brogdon",
    "Kobe Bufkin",
    "Carlton Carrington",
    "Michael Carter-Williams",
    "Alex Caruso",
    "Nicolas Claxton",
    "Isaiah Collier",
    "Spencer Dinwiddie",
    "Luka Doncic",
    "A.J. Green",
    "Jalen Green",
    "Tyrese Haliburton",
    "Penny Hardaway",
    "James Harden",
    "Josh Hart",
    "Jordan Hawkins",
    "Killian Hayes",
    "Tyler Herro",
    "Jrue Holiday",
    "Ty Jerome",
    "Zach LaVine",
    "Damion Lee",
    "Terance Mann",
    "Shake Milton",
    "Ajay Mitchell",
    "Dejounte Murray",
    "Andrew Nembhard",
    "Daishen Nix",
    "Brandin Podziemski",
    "Michael Porter Jr.",
    "Trevelin Queen",
    "Austin Reaves",
    "Oscar Robertson",
    "Nick Smith Jr.",
    "Jalen Suggs",
    "Chris Webber",
    "Blake Wesley",
    "Alondes Williams",
    "Delon Wright",
    "Beluba",
    "Chris Brickley",
    "J. Cole",
    "LD2K",
    "Ronnie 2K",
    "Dan Rue",
    "L. Shooter",
    "Precious Achiuwa",
    "Bam Adebayo",
    "Ochai Agbaji",
    "Ray Allen",
    "Kyle Anderson",
    "Thanasis Antetokounmpo",
    "Carmelo Anthony",
    "OG Anunoby",
    "Trevor Ariza",
    "Deni Avdija",
    "Patrick Baldwin Jr.",
    "Desmond Bane",
    "Dominick Barlow",
    "Harrison Barnes",
    "Scottie Barnes",
    "RJ Barrett",
    "Will Barton",
    "Charles Bassey",
    "Ketia Bates-Diop",
    "Nicolas Batum",
    "Darius Bazley",
    "MarJon Beauchamp",
    "Saddiq Bey",
    "Khem Birch",
    "Larry Bird",
    "Onuralp Bitim",
    "Bismack Biyombo",
    "Anthony Black",
    "Bogdan Bogdanovic",
    "Bojan Bogdanovic",
    "Leandro Bolmaro",
    "Adem Bona",
    "Isaac Bonga",
    "Brandon Boston Jr.",
    "Chris Boucher",
    "Elton Brand",
    "Malaki Branham",
    "Christian Braun",
    "Mikal Bridges",
    "Miles Bridges",
    "Oshae Brissett",
    "Dillon Brooks",
    "Charles Brown Jr.",
    "Greg Brown",
    "Jaylen Brown",
    "Kobe Brown",
    "Sterling Brown",
    "Troy Brown Jr.",
    "Kobe Bryant",
    "Reggie Bullock",
    "Alec Burks",
    "Jimmy Butler",
    "Matas Buzelis",
    "Kentavious Caldwell-Pope",
    "Vlatko Cancar",
    "Vernon Carey Jr.",
    "Stephon Castle",
    "Julian Champagnie",
    "Cam Christie",
    "Max Christie",
    "Brandon Clarke",
    "Amir Coffey",
    "John Collins",
    "Pat Connaughton",
    "Bilal Coulibaly",
    "Rickey Council IV",
    "Robert Covington",
    "Torrey Craig",
    "Jae Crowder",
    "Jarrett Culver",
    "Cade Cunningham",
    "Tristan da Silva",
    "Pacome Dadiet",
    "Dyson Daniels",
    "DeMar Derozan",
    "Hamidou Diallo",
    "Gradey Dick",
    "Ousmane Dieng",
    "P.J. Dozier",
    "Clyde Drexler",
    "Chris Duarte",
    "Ryan Dunn",
    "Kevin Durant",
    "Tari Eason",
    "Kessler Edwards",
    "Drew Eubanks",
    "Dante Exum",
    "Derrick Favors",
    "Bruno Fernando",
    "Dorian Finney-Smith",
    "Simone Fontecchio",
    "Evan Fournier",
    "Enrique Freeman",
    "Johnny Furphy",
    "Wenyen Gabriel",
    "Daniel Gafford",
    "Usman Garuba",
    "Rudy Gay",
    "Kyshawn George",
    "Paul George",
    "Taj Gibson",
    "Josh Giddey",
    "Anthony Gill",
    "Aaron Gordon",
    "Jerami Grant",
    "Danny Green",
    "Draymond Green",
    "JaMychal Green",
    "Javonte Green",
    "Jeff Green",
    "Josh Green",
    "A.J. Griffin",
    "Rui Hachimura",
    "Tim Hardaway Jr.",
    "Montrezl Harrell",
    "Joe Harris",
    "Tobias Harris",
    "Udonis Haslem",
    "Sam Hauser",
    "Gordan Hayward",
    "Taylor Henddricks",
    "Juan Hernangomez",
    "Justin Holiday",
    "Ron Holland",
    "Rodney Hood",
    "Jalen Hood-Schifino",
    "Al Horford",
    "Danuel House",
    "Caleb Houstan",
    "Jett Howard",
    "Kevin Huerter",
    "De'Andre Hunter",
    "Joe Ingles",
    "Brandon Ingram",
    "Harrison Ingram",
    "G.G. Jackson",
    "Josh Jackson",
    "Justin Jackson",
    "LeBron James",
    "Jaime Jaquez Jr.",
    "DeJon Jarreau",
    "AJ Johnson",
    "Alize Johnson",
    "Cameron Johnson",
    "Jalen Johnson",
    "James Johnson",
    "Keldon Johnson",
    "Magic Johnson",
    "Stanley Johnson",
    "Colby Jones",
    "Dillon Jones",
    "Derrick Jones Jr.",
    "Herbert Jones",
    "Michael Jordan",
    "Nikola Jovic",
    "Johnny Juzang",
    "Luke Kennard",
    "Corey Kispert",
    "Bobi Klintman",
    "Dalton Knecht",
    "Kevin Knox II",
    "John Konchar",
    "Furkan Korkmaz",
    "Kyle Korver",
    "Toni Kukoc",
    "Jonathan Kuminga",
    "Kyle Kuzma",
    "Romeo Langford",
    "Jake LaRavia",
    "Pelle Larsson",
    "A.J. Lawson",
    "Kawhi Leonard",
    "Caris LeVert",
    "Nassir Little",
    "Isaiah Livers",
    "Kenneth Lofton Jr.",
    "Kevon Looney",
    "Kevin Love",
    "Trey Lyles",
    "Karl Malone",
    "Shawn Marion",
    "Naji Marshall",
    "Caleb Martin",
    "Cody Martin",
    "Kenyon Martin Jr.",
    "Kevin Martin",
    "Garrison Mathews",
    "Bennedict Mathurin",
    "Jaden McDaniels",
    "Jalen McDaniels",
    "Doug McDermott",
    "Bryce McGowens",
    "Chimezie Metu",
    "Khris Middleton",
    "Brandon Miller",
    "Paul Millsap",
    "Justin Minaya",
    "Moses Moody",
    "Taze Moore",
    "Wendell Moore Jr",
    "Marcus Morris Sr.",
    "Markieff Morris",
    "Chris Mullin",
    "Trey Murphy III",
    "Keegan Murray",
    "Kris Murray",
    "Sviatoslav Mykhailiuk",
    "Larry Nance Jr.",
    "Aaron Nesmith",
    "Tristen Newton",
    "Georges Niang",
    "Zeke Nnaji",
    "Jordan Nwora",
    "Charles Oakley",
    "Lamar Odom",
    "Chuma Okeke",
    "Isaac Okoro",
    "KZ Okpala",
    "Euguene Omoruyi",
    "Royce O'Neale",
    "Cedi Osman",
    "Kelly Oubre Jr.",
    "Sam Perkins",
    "Julian Phillips",
    "Paul Pierce",
    "Theo Pinson",
    "Scottie Pippen",
    "Otto Porter",
    "Micah Potter",
    "Taurean Prince",
    "Oliver-Maxence Prosper",
    "Lester Quinones",
    "Vladimir Radmanovic",
    "Julius Randle",
    "Zach Randolph",
    "Duop Reath",
    "Cameron Reddish",
    "Davon Reed",
    "Paul Reed",
    "Antonio Reeves",
    "Naz Reid",
    "Josh Richardson",
    "Zaccharie Risacher",
    "Duncan Robison",
    "Glenn Robinson III",
    "Jeremiah Robinson-Earl",
    "Isaiah Roby",
    "David Roddy",
    "Terrence Ross",
    "Rayan Rupert",
    "Matt Ryan",
    "Tidjane Salaun",
    "Baylor Scheierman",
    "Admiral Schofield",
    "Jay Scrubb",
    "Brice Sensabaugh",
    "Terrence Shannon Jr.",
    "Day'Ron Sharpe",
    "Shaedon Sharpe",
    "Ben Sheppard",
    "Pascal Siakam",
    "Ben Simmons",
    "J.R. Smith",
    "Tyler Smith",
    "Jeremy Sochan",
    "Lamar Stevens",
    "Isaiah Stewart",
    "Julian Strawther",
    "Max Strus",
    "Cole Swider",
    "Jayson Tatum",
    "Garrett Temple",
    "Dalen Terry",
    "Daniel Theis",
    "Amen Thompson",
    "Ausar Thompson",
    "Klay Thompson",
    "Tristan Thompson",
    "JT Thor",
    "Matisse Thybulle",
    "Xavier Tillman",
    "Isaiah Todd",
    "Nikola Topic",
    "Obi Toppin",
    "Juan Toscano",
    "Gary Trent Jr.",
    "PJ Tucker",
    "Jaylon Tyson",
    "Jarred Vanderbilt",
    "Devin Vassell",
    "Sasha Vezkenkov",
    "Dean Wade",
    "Franz Wagner",
    "Jabari Walker",
    "Jarace Walker",
    "TJ Warren",
    "PJ Washington",
    "Yuta Watanabe",
    "Lindy Waters III",
    "Trendon Watford",
    "Peyton Watson",
    "Jaylen Wells",
    "David West",
    "Dariq Whitehead",
    "Cam Whitmore",
    "Andrew Wiggins",
    "Dominique Wilkins",
    "Cody Williams",
    "Grant Williams",
    "Jalen Williams",
    "Jaylin Williams",
    "Kenrich Williams",
    "Patrick Williams",
    "Robert Williams III",
    "Ziaire Williams",
    "Zion Williamson",
    "Dylan Windler",
    "Justise Winslow",
    "Christian Wood",
    "Thaddeus Young"
],
real_range(82, 88): [
    "Dalano Banton",
    "Zach LaVine",
    "Terance Mann",
    "Michael Porter Jr.",
    "Beluba",
    "Chris Brickley",
    "J. Cole",
    "LD2K",
    "Ronnie 2K",
    "Dan Rue",
    "L. Shooter",
    "Precious Achiuwa",
    "Bam Adebayo",
    "Thanasis Antetokounmpo",
    "Dominick Barlow",
    "Charles Bassey",
    "Khem Birch",
    "Larry Bird",
    "Bismack Biyombo",
    "Chris Boucher",
    "Elton Brand",
    "Oshae Brissett",
    "Matas Buzelis",
    "Vernon Carey Jr.",
    "Brandon Clarke",
    "John Collins",
    "Robert Covington",
    "Ousmane Dieng",
    "Kevin Durant",
    "Drew Eubanks",
    "Derrick Favors",
    "Bruno Fernando",
    "Daniel Gafford",
    "Usman Garuba",
    "Taj Gibson",
    "Draymond Green",
    "JaMychal Green",
    "Montrezl Harrell",
    "Udonis Haslem",
    "Taylor Henddricks",
    "Al Horford",
    "G.G. Jackson",
    "Alize Johnson",
    "James Johnson",
    "Stanley Johnson",
    "Nikola Jovic",
    "Toni Kukoc",
    "Caris LeVert",
    "Kevon Looney",
    "Kevin Love",
    "Trey Lyles",
    "Karl Malone",
    "Kenyon Martin Jr.",
    "Chimezie Metu",
    "Paul Millsap",
    "Marcus Morris Sr.",
    "Markieff Morris",
    "Zeke Nnaji",
    "Charles Oakley",
    "Lamar Odom",
    "Sam Perkins",
    "Micah Potter",
    "Vladimir Radmanovic",
    "Julius Randle",
    "Zach Randolph",
    "Duop Reath",
    "Paul Reed",
    "Naz Reid",
    "Jeremiah Robinson-Earl",
    "Isaiah Roby",
    "Day'Ron Sharpe",
    "Pascal Siakam",
    "Ben Simmons",
    "Isaiah Stewart",
    "Daniel Theis",
    "Tristan Thompson",
    "Xavier Tillman",
    "Isaiah Todd",
    "Obi Toppin",
    "PJ Tucker",
    "Jarred Vanderbilt",
    "Franz Wagner",
    "PJ Washington",
    "David West",
    "Grant Williams",
    "Jaylin Williams",
    "Robert Williams III",
    "Zion Williamson",
    "Justise Winslow",
    "Christian Wood",
    "Thaddeus Young",
    "Kareem Abdul-Jabbar",
    "Steven Adams",
    "Santi Aldama",
    "LaMarcus Aldridge",
    "Jarrett Allen",
    "Giannis Antetokounmpo",
    "Deandre Ayton",
    "Udoka Azubuike",
    "Ibou Badji",
    "Marvin Bagley III",
    "Mohamed Bamba",
    "Paolo Banchero",
    "Davis Bertans",
    "Goga Bitadze",
    "Bol Bol",
    "Chris Bosh",
    "Tony Bradley",
    "Thomas Bryant",
    "Clint Capela",
    "Wendell Carter Jr.",
    "Donovan Clingan",
    "Noah Clowney",
    "Zach Collins",
    "DeMarcus Cousins",
    "Anthony Davis",
    "Dewayne Dedmon",
    "Gorgui Dieng",
    "Andre Drummond",
    "Kevin Duckworth",
    "Tim Duncan",
    "Jalen Duren",
    "Zach Edey",
    "Joel Embiid",
    "Patrick Ewing",
    "Kyle Flipowski",
    "Danilo Gallinari",
    "Kevin Garnett",
    "Marc Gasol",
    "Pau Gasol",
    "Harry Giles",
    "Rudy Gobert",
    "Isaiah Hartenstein",
    "Jaxson Hayes",
    "Willy Hernangomez",
    "Daron Holmes II",
    "Richaun Holmes",
    "Chet Holgren",
    "Dwight Howard",
    "Jay Huff",
    "Oso Ighodaro",
    "Jonathan Isaac",
    "Isaiah Jackson",
    "Jaren Jackson Jr.",
    "Nikola Jokic",
    "Damian Jones",
    "Kai Jones",
    "DeAndre Jordan",
    "Walker Kessler",
    "Maxi Kleber",
    "Nathan Knight",
    "Luke Kornet",
    "Bill Laimbeer",
    "Jock Landale",
    "Alex Len",
    "Rashard Lewis",
    "Dereck Lively II",
    "Brook Lopez",
    "Robin Lopez",
    "Sandro Mamukelashvili",
    "Boban Marjanovic",
    "Lauri Markkanen",
    "JaVale McGee",
    "Yves Missi",
    "Evan Mobley",
    "Mike Muscala",
    "Jaokim Noah",
    "Nerlens Noel",
    "Dirk Nowitzki",
    "Jusuf Nurkic",
    "Kelly Olynyk",
    "Shaquille O'Neal",
    "Mason Plumlee",
    "Jakob Poeltl",
    "Aleksej Pokusevski",
    "Bobby Portis Jr.",
    "Kristaps Porzingus",
    "Dwight Powell",
    "Neemias Queta",
    "Nick Richards",
    "David Robinson",
    "Mitchell Robinson",
    "Domantas Sabonis",
    "Luka Samanic",
    "Dario Saric",
    "Alexandre Sarr",
    "Olivier Sarr",
    "Alperen Sengun",
    "Jabari Smith Jr.",
    "Jalen Smith",
    "Amar'e Stoudemire",
    "Karl-Anthony Towns",
    "Myles Turner",
    "Jonas Valanciunas",
    "Nikola Vucevic",
    "Moritz Wagner",
    "Kelel Ware",
    "Hassan Whiteside",
    "D.J. Wilson",
    "James Wiseman",
    "Omer Yurtseven",
    "Cody Zeller",
    "Ivica Zubac"
],
}

free_throw_list = [
    "Bam Adebayo",
    "LaMarcus Aldridge",
    "Ray Allen",
    "Grayson Allen",
    "Jarrett Allen",
    "Giannis Antetokounmpo",
    "Carmelo Anthony",
    "Cole Anthony",
    "Gilbert Arenas",
    "Marvein Bagley II",
    "LaMelo Ball",
    "Paolo Banchero",
    "Desmond Bane",
    "Scottie Barnes",
    "Harrison Barnes",
    "RJ Barrett",
    "Rick Barry",
    "Bradley Beal",
    "Malik Beasley",
    "Patrick Beverly",
    "Larry Bird",
    "Bogdan Bogdanovic",
    "Bojan Bogdanovic",
    "Devin Booker",
    "Chris Boucher",
    "Chris Bosh",
    "Dillon Brooks",
    "Jaylen Brown",
    "Jalen Brunson",
    "Kobe Bryant",
    "Jimmy Butler",
    "Kentavious Caldwell-Pope",
    "Vince Carter",
    "Wendell Carter Jr.",
    "Bill Cartwright",
    "Wilt Chamberlain",
    "Marquese Chriss",
    "Brandon Clarke",
    "Jordan Clarkson",
    "Nicolas Claxton",
    "J. Cole",
    "John Collins",
    "DeMarcus Cousins",
    "Bob Cousy",
    "Jamal Crawford",
    "Cade Cunningham",
    "Stephen Curry",
    "Adrian Dantley",
    "Anthony Davis",
    "DeMar DeRozan",
    "Spencer Dinwiddie",
    "Luka Doncic",
    "Luguentz Dort",
    "Tim Duncan",
    "Kevin Durant",
    "Jalen Duren",
    "Anthony Edwards",
    "Joel Embiid",
    "Tacko Fall",
    "Dorian Finney-Smith",
    "De’Aaron Fox",
    "Rick Fox",
    "Markelle Fultz",
    "Danilo Gallinari",
    "Kevin Garnett",
    "Pau Gasol",
    "Rudy Gay",
    "Paul George",
    "Josh Giddey",
    "Rudy Gobert",
    "Aaron Gordon",
    "Draymond Green",
    "Jalen Green",
    "Blake Griffin",
    "Tyrese Haliburton",
    "Richard Hamilton",
    "Tim Hardaway Jr.",
    "James Harden",
    "Isaiah Hartenstein",
    "Chuck Hayes",
    "Scoot Henderson",
    "Tyler Herro",
    "Buddy Hield",
    "Jrue Holiday",
    "Al Horford",
    "Jeff Hornacek",
    "Dwight Howard",
    "Kevin Huerter",
    "De'Andre Hunter",
    "Andre Iguodala",
    "Kyrie Irving",
    "Jaden Ivey",
    "Jaren Jackson Jr."
    "LeBron James",
    "Cameron Johnson",
    "Joe Johnson",
    "Keldon Johnson",
    "Magic Johnson",
    "Nikola Jokic",
    "DeAndre Jordan",
    "Michael Jordan",
    "Jason Kidd",
    "Maxi Kleber",
    "Kyle Korver",
    "Kyle Kuzma",
    "Zach LaVine",
    "Kawhi Leonard",
    "Damian Lillard",
    "Kevon Looney",
    "Brook Lopez",
    "Kevin Love",
    "Kyle Lowry",
    "Karl Malone",
    "Terance Mann",
    "Lauri Markkanen",
    "Shawn Marion",
    "Kevin Martin",
    "Jaden McDaniels",
    "Bennedict Mathurin",    
    "Khris Middleton",
    "Donovan Mitchell",
    "Evan Mobley",
    "Ja Morant",
    "Monte Morris",
    "Alonzo Mourning",
    "Jamal Murray",
    "Keegan Murray",
    "Steve Nash",
    "Don Nelson",
    "Joakim Noah",
    "Dirk Nowitzki",
    "Jusuf Nurkic",
    "Onyeka Okongwu",
    "Isaac Okoro",
    "Shaquille O’Neal",
    "Royce O’Neal",
    "Tony Parker",
    "Chris Paul",
    "Scottie Pippen",
    "Paul Pierce",
    "Jakob Poeltl",
    "Kristaps Porzingis",
    "Jordan Poole",
    "Norman Powell",
    "Julius Randle",
    "Zach Randolph",
    "Austin Reaves",
    "Cameron Reddish",
    "Duncan Robinson",
    "Nate Robinson",
    "Derrick Rose",
    "Terry Rozier III",
    "Ricky Rubio",
    "D’Angelo Russell",
    "Domantas Sabonis",
    "Collin Sexton",
    "Shaedon Sharpe",
    "Anfernee Simons",
    "Ben Simmons",
    "J.R. Smith",
    "Jabari Smith Jr.",
    "John Stockton",
    "Jayson Tatum",
    "Klay Thompson",
    "Obi Toppin",
    "Karl-Anthony Towns",
    "Myles Turner",
    "Jarred Vanderbilt",
    "Devin Vassell",
    "Nikola Vucevic",
    "Dwyane Wade",
    "Franz Wagner",
    "Moritz Wagner",
    "Kemba Walker",
    "John Wall",
    "PJ Washington",
    "Russell Westbrook",
    "Coby White",
    "Andrew Wiggins",
    "Jamaal Wilkes",
    "Jalen Williams",
    "Jason Williams",
    "Jaylin Williams",
    "Patrick Williams",
    "Robert Williams",
    "Zion Williamson",
    "Trae Young",
    "Ivica Zubac",
    "Underhand",
    "Candace Parker",
    "Breanna Stewart",
    "Free Throw WNBA 1",
    "Free Throw WNBA 2",
]

# Weighted list of jumpshot timings
jumpshot_timing_list = (
    ["Very Slow"] * 5 + 
    ["Slow"] * 10 + 
    ["Normal"] * 75 +
    ["Quick"] * 5 +
    ["Very Quick"] * 5
)

# Gets a random jumpshot based on the height then returns the jumpshot
def jumpshot_roll(height):
    for height_range, jumpshots in jumpshot_list.items():
        if height in height_range:
            return random.choice(jumpshots)

# Gets a random jumpshot timing from 0 to 100
def timing_roll():
    return random.choice(jumpshot_timing_list)

# Gets a random jumpshot blending from 0 to 100
def blending_roll():
    return random.randint(0, 100)

# Gets a random free throw from the free throw list
def free_throw_roll():
    return random.choice(free_throw_list)

# Returns a player with randomly generated jumpshot fields
def generate_jumpshot(player):
    player.jumpshot = jumpshot_roll(player.height)
    player.jumpshot_release_1 = jumpshot_roll(player.height)
    player.jumpshot_release_2 = jumpshot_roll(player.height)
    player.jumpshot_blending = blending_roll()
    player.jumpshot_timing = timing_roll()
    player.jumpshot_free_throw = free_throw_roll()
    return player
