# Django model choices
position_choices = ["PG", "SG", "SF", "PF", "C"]
country_choices = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "American Samoa",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antarctica (the territory South of 60 deg S)",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Bouvet Island (Bouvetoya)",
    "Brazil",
    "British Indian Ocean Territory (Chagos Archipelago)",
    "British Virgin Islands",
    "Brunei Darussalam",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Cayman Islands",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Christmas Island",
    "Cocos (Keeling) Islands",
    "Colombia",
    "Comoros",
    "Congo",
    "Congo",
    "Cook Islands",
    "Costa Rica",
    "Cote d'Ivoire",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Faroe Islands",
    "Falkland Islands (Malvinas)",
    "Fiji",
    "Finland",
    "France",
    "French Guiana",
    "French Polynesia",
    "French Southern Territories",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Heard Island and McDonald Islands",
    "Holy See (Vatican City State)",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea",
    "Korea",
    "Kuwait",
    "Kyrgyz Republic",
    "Lao People's Democratic Republic",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libyan Arab Jamahiriya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macao",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Martinique",
    "Mauritania",
    "Mauritius",
    "Mayotte",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands Antilles",
    "Netherlands",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Niue",
    "Norfolk Island",
    "North Macedonia",
    "Northern Mariana Islands",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestinian Territory",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Pitcairn Islands",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Reunion",
    "Romania",
    "Russian Federation",
    "Rwanda",
    "Saint Barthelemy",
    "Saint Helena",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Martin",
    "Saint Pierre and Miquelon",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia (Slovak Republic)",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Georgia and the South Sandwich Islands",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Svalbard & Jan Mayen Islands",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syrian Arab Republic",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks and Caicos Islands",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States of America",
    "United States Minor Outlying Islands",
    "United States Virgin Islands",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Wallis and Futuna",
    "Western Sahara",
    "Yemen",
    "Zambia",
    "Zimbabwe",
]
college_choices = [
    "N/A",
    "Other",
    "University of Alabama",
    "Arizona State University",
    "University of Arizona",
    "University of Arkansas",
    "Auburn University",
    "Baylor University",
    "Boise State University",
    "College of Charleston",
    "Colgate University",
    "Creighton University",
    "Drake University",
    "Duke University",
    "Fairleigh Dickinson University",
    "Florida Atlantic University",
    "Furman University",
    "Gonzaga University",
    "Grand Canyon University",
    "Howard University",
    "University of Houston",
    "University of Illinois Urbana-Champaign",
    "Indiana University Bloomington",
    "Iona College",
    "Iowa State University",
    "University of Iowa",
    "Kansas State University",
    "University of Kansas",
    "Kennesaw State University",
    "University of Kentucky",
    "Lafayette College",
    "Liberty University",
    "Louisiana State University",
    "Marquette University",
    "University of Maryland, College Park",
    "University of Memphis",
    "University of Miami",
    "Michigan State University",
    "University of Missouri",
    "Montana State University",
    "University of Nevada, Las Vegas",
    "University of Nevada, Reno",
    "North Carolina State University",
    "University of North Carolina at Chapel Hill",
    "Northwestern University",
    "Ohio State University",
    "Oral Roberts University",
    "Pennsylvania State University",
    "Princeton University",
    "Providence College",
    "Purdue University",
    "San Diego State University",
    "University of South Carolina",
    "University of Southern California",
    "University of Tennessee",
    "Texas A&M University",
    "University of Texas at Austin",
    "Texas Christian University",
    "Texas Southern University",
    "University of California, Los Angeles",
    "University of Connecticut",
    "University of Vermont",
    "Villanova University",
    "Virginia Commonwealth University",
    "University of Virginia",
    "West Virginia University",
    "College of William & Mary",
    "University of Wisconsin-Madison",
    "Xavier University",
    "Yale University",
]
playoff_round_choices = ["Quarterfinals", "Semifinals", "Finals"]

# Callable for attributes
def default_attributes():
    return {
        "Driving Layup": 55,
        "Post Fade": 55,
        "Post Hook": 55,
        "Post Moves": 55,
        "Draw Foul": 55,
        "Close Shot": 55,
        "Midrange Shot": 55,
        "3pt Shot": 55,
        "Free Throw": 55,
        "Ball Control": 55,
        "Passing IQ": 55,
        "Pass Accuracy": 55,
        "Offensive Rebound": 55,
        "Standing Dunk": 55,
        "Driving Dunk": 55,
        "Shot IQ": 55,
        "Passing Vision": 55,
        "Hands": 55,
        "Defensive Rebound": 55,
        "Interior Defense": 55,
        "Perimeter Defense": 55,
        "Block": 55,
        "Steal": 55,
        "Speed with Ball": 55,
        "Hustle": 55,
        "Pass Perception": 55,
        "Defensive Consistency": 55,
        "Help Defense IQ": 55,
        "Offensive Consistency": 55,
        "Intangibles": 55,
        "Speed": 55,
        "Agility": 55,
        "Vertical": 55,
        "Strength": 55,
    }

# Callable for badges
def default_badges():
    return {
        # Shooting badges
        "Agent 3": 0,
        "Blinders": 0,
        "Catch & Shoot": 0,
        "Claymore": 0,
        "Comeback Kid": 0,
        "Corner Specialist": 0,
        "Deadeye": 0,
        "Free Points": 0,
        "Green Machine": 0,
        "Guard Up": 0,
        "Limitless Range": 0,
        "Middy Magician": 0,
        "Open Looks": 0,
        "Post Fade Phenom": 0,
        "Slippery Off-Ball": 0,
        "Space Creator": 0,
        "Spot Finder": 0,
        # Playmaking badges
        "Ankle Breaker": 0,
        "Bail Out": 0,
        "Blow-By": 0,
        "Break Starter": 0,
        "Dimer": 0,
        "Handles for Days": 0,
        "Hyperdrive": 0,
        "Killer Combos": 0,
        "Needle Threader": 0,
        "Physical Handles": 0,
        "Post Playmaker": 0,
        "Relay Passer": 0,
        "Special Delivery": 0,
        "Speed Booster": 0,
        "Touch Passer": 0,
        "Triple Spike": 0,
        "Unpluckable": 0,
        # Finishing badges
        "Acrobat": 0,
        "Aerial Wizard": 0,
        "Backdown Punisher": 0,
        "Big Driver": 0,
        "Bulldozer": 0,
        "Bunny": 0,
        "Dream Shake": 0,
        "Dropstepper": 0,
        "Fast Twitch": 0,
        "Fearless Finisher": 0,
        "Float Game": 0,
        "Giant Slayer": 0,
        "Hook Specialist": 0,
        "Masher": 0,
        "Post Spin Technician": 0,
        "Posterizer": 0,
        "Precision Dunker": 0,
        "Pro Touch": 0,
        "Rise Up": 0,
        "Scooper": 0,
        "Slithery": 0,
        "Spin Cycle": 0,
        "Two Step": 0,
        "Whistle": 0,
        #  Defensive badges
        "94 Feet": 0,
        "Anchor": 0,
        "Ankle Braces": 0,
        "Boxout Beast": 0,
        "Brick Wall": 0,
        "Challenger": 0,
        "Chase Down Artist": 0,
        "Clamps": 0,
        "Fast Feet": 0,
        "Glove": 0,
        "Interceptor": 0,
        "Immovable Enforcer": 0,
        "Off-Ball Pest": 0,
        "Pick Dodger": 0,
        "Pogo Stick": 0,
        "Post Lockdown": 0,
        "Rebound Chaser": 0,
        "Right Stick Ripper": 0,
        "Work Horse": 0,
    }


# Callable for tendencies
def default_tendencies():
    return {
        # Inside tendencies
        "Standing Dunk Tendency": 50,
        "Driving Dunk Tendency": 50,
        "Flashy Dunk": 50,
        "Alley-Oop": 50,
        "Putback Dunk": 50,
        "Crash": 50,
        "Driving Layup Tendency": 50,
        "Spin Layup": 50,
        "Hop Step Layup": 50,
        "Euro Step Layup": 50,
        "Floater": 50,
        # Shooting tendencies
        "Step Through Shot": 50,
        "Shot Under Basket": 50,
        "Shot Close": 50,
        "Shot Close Left": 50,
        "Shot Close Middle": 50,
        "Shot Close Right": 50,
        "Shot Mid": 50,
        "Spot Up Shot Mid": 50,
        "Off Screen Shot Mid": 50,
        "Shot 3pt": 50,
        "Spot Up Shot 3pt": 50,
        "Off Screen Shot 3pt": 50,
        "Contested Jumper Mid": 50,
        "Contested Jumper 3pt": 50,
        "Stepback Jumper Mid": 50,
        "Stepback Jumper 3pt": 50,
        "Spin Jumper": 50,
        "Transition Pull Up 3pt": 50,
        "Drive Pull Up 3pt": 50,
        "Drive Pull Up Mid": 50,
        "Use Glass": 50,
        # Defensive tendencies
        "Pass Interception": 50,
        "Take Charge": 50,
        "On Ball Steal": 50,
        "Contest Shot": 50,
        "Block Shot": 50,
        "Foul": 50,
        "Hard Foul": 50,
        # Iso Tendencies
        "Triple Threat Pump Fake": 50,
        "Triple Threat Jab Step": 50,
        "Triple Threat Idle": 50,
        "Triple Threat Shoot": 50,
        "Setup With Sizeup": 50,
        "Setup With Hesitation": 50,
        "No Setup Dribble": 50,
        # Post tendencies
        "Post Up": 50,
        "Post Shimmy Shot": 50,
        "Post Face Up": 50,
        "Post Back Down": 50,
        "Post Aggressive Backdown": 50,
        "Shoot From Post": 50,
        "Post Hook Left": 50,
        "Post Hook Right": 50,
        "Post Fade Left": 50,
        "Post Fade Right": 50,
        "Post Up And Under": 50,
        "Post Hop Shot": 50,
        "Post Step Back Shot": 50,
        "Post Drive": 50,
        "Post Spin": 50,
        "Post Drop Step": 50,
        "Post Hop Step": 50,
        # Freelance tendencies
        "Shoot": 50,
        "Touches": 50,
        "Roll Vs Pop": 50,
        "Transition Spot Up": 50,
        "Iso Vs Elite Defender": 50,
        "Iso Vs Good Defender": 50,
        "Iso Vs Average Defender": 50,
        "Iso Vs Poor Defender": 50,
        "Play Discipline": 50,
        # Passing tendencies
        "Dish To Open Man": 50,
        "Flashy Pass": 50,
        "Alley Oop Pass": 50,
        # Drive tendencies
        "Drive": 50,
        "Spot Up Drive": 50,
        "Off Screen Drive": 50,
        "Drive Right": 50,
        "Driving Crossover": 50,
        "Driving Spin": 50,
        "Driving Step Back": 50,
        "Driving Half Spin": 50,
        "Driving Double Crossover": 50,
        "Driving Behind The Back": 50,
        "Driving Dribble Hesitation": 50,
        "Driving In And Out": 50,
        "No Driving Dribble Move": 50,
        "Attack Strong On Drive": 50
    }


# Callable for modifications
def default_modifications():
    return {}

# Callable for game highs
def default_game_highs():
    return {
        "game_id": 0,
        "label": "N/A",
    }

# Callables for default team log fields
def default_lineup():
    return {
        "PG": {"player": "None", "touches": 50, "initiator": "No", "playtype_1": "N/A", "playtype_2": "N/A", "playtype_3": "N/A", "playtype_4": "N/A"},
        "SG": {"player": "None", "touches": 50, "initiator": "No", "playtype_1": "N/A", "playtype_2": "N/A", "playtype_3": "N/A", "playtype_4": "N/A"},
        "SF": {"player": "None", "touches": 50, "initiator": "No", "playtype_1": "N/A", "playtype_2": "N/A", "playtype_3": "N/A", "playtype_4": "N/A"},
        "PF": {"player": "None", "touches": 50, "initiator": "No", "playtype_1": "N/A", "playtype_2": "N/A", "playtype_3": "N/A", "playtype_4": "N/A"},
        "C": {"player": "None", "touches": 50, "initiator": "No", "playtype_1": "N/A", "playtype_2": "N/A", "playtype_3": "N/A", "playtype_4": "N/A"},
    }