# Generated by Django 5.0.3 on 2024-06-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.URLField(default='https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
