# Generated by Django 5.0.3 on 2024-07-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_customuser_avatar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="can_edit_stats",
            field=models.BooleanField(default=False),
        ),
    ]
