# Generated by Django 5.0.3 on 2024-08-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customuser_can_edit_past_games"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="can_edit_past_games",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="can_edit_stats",
        ),
        migrations.AddField(
            model_name="customuser",
            name="auto_collect_for",
            field=models.BooleanField(default=False),
        ),
    ]
