# Generated by Django 5.0.3 on 2024-09-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_rename_auto_collect_for_customuser_has_care_package"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="has_second_player_slot",
            field=models.BooleanField(default=False),
        ),
    ]
