# Generated by Django 5.0.3 on 2024-09-27 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_customuser_has_second_player_slot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="sp",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="xp",
        ),
    ]
