# Generated by Django 5.0.3 on 2024-06-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentlog',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='upgradelog',
            old_name='created_at',
            new_name='created',
        ),
    ]
