# Generated by Django 5.0.3 on 2024-06-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_paymentlog_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='season',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='week',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='upgradelog',
            name='season',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='upgradelog',
            name='week',
            field=models.IntegerField(default=1),
        ),
    ]
