# Generated by Django 5.0.3 on 2024-06-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_paymentlog_season_paymentlog_week_upgradelog_season_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upgradelog',
            old_name='total',
            new_name='total_sp',
        ),
        migrations.AddField(
            model_name='upgradelog',
            name='total_xp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
