# Generated by Django 5.0.3 on 2024-06-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_rename_total_upgradelog_total_sp_upgradelog_total_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='reason',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
