# Generated by Django 5.0.3 on 2024-06-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_paymentlog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='type',
            field=models.CharField(choices=[('SP', 'SP'), ('XP', 'XP')], max_length=12),
        ),
    ]
