# Generated by Django 5.0.3 on 2024-06-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0009_alter_paymentlog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='type',
            field=models.CharField(max_length=2),
        ),
    ]
