# Generated by Django 5.0.3 on 2024-06-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0010_alter_paymentlog_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgradelog',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
