# Generated by Django 5.0.3 on 2024-06-30 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0012_modificationlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModificationLog',
        ),
    ]
