# Generated by Django 5.0.3 on 2024-07-05 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0013_delete_modificationlog'),
        ('players', '0027_alter_player_modifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('length', models.IntegerField()),
                ('option', models.IntegerField(default='None')),
                ('current_year_payment', models.IntegerField()),
                ('subsequent_year_payment', models.IntegerField()),
                ('biennium_year_payment', models.IntegerField()),
                ('no_trade_clause', models.BooleanField(default=False)),
                ('no_release_clause', models.BooleanField(default=False)),
                ('incentives', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
        ),
    ]
