# Generated by Django 5.0.3 on 2024-07-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0014_contractlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractlog',
            name='player',
        ),
        migrations.AddField(
            model_name='contractlog',
            name='weeks_paid',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
