# Generated by Django 5.0.3 on 2024-07-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0015_remove_contractlog_player_contractlog_weeks_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractlog',
            name='biennium_year_payment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contractlog',
            name='subsequent_year_payment',
            field=models.IntegerField(default=0),
        ),
    ]
