# Generated by Django 5.0.3 on 2024-07-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0016_alter_contractlog_biennium_year_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractlog',
            name='option',
            field=models.CharField(default='None', max_length=32),
        ),
    ]
