# Generated by Django 5.0.3 on 2024-07-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0018_contractlog_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='week',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='upgradelog',
            name='week',
            field=models.IntegerField(default=3),
        ),
    ]
