# Generated by Django 5.0.3 on 2024-07-26 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0024_alter_paymentlog_week_alter_upgradelog_week"),
        ("players", "0033_alter_player_coach_suggestion_attributes_and_more"),
        ("teams", "0006_team_surge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentlog",
            name="week",
            field=models.IntegerField(default=15.5),
        ),
        migrations.AlterField(
            model_name="upgradelog",
            name="week",
            field=models.IntegerField(default=15.5),
        ),
        migrations.CreateModel(
            name="TransactionMoveLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approved", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "released",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="released",
                        to="players.player",
                    ),
                ),
                (
                    "signed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signed",
                        to="players.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="teams.team"
                    ),
                ),
            ],
        ),
    ]
