# Generated by Django 5.0.3 on 2024-07-26 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0025_alter_paymentlog_week_alter_upgradelog_week_and_more"),
        ("players", "0033_alter_player_coach_suggestion_attributes_and_more"),
        ("teams", "0006_team_surge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionmovelog",
            name="approved",
            field=models.BooleanField(
                default=False, help_text="Whether the transaction has been approved."
            ),
        ),
        migrations.AlterField(
            model_name="transactionmovelog",
            name="released",
            field=models.ForeignKey(
                help_text="The player being released.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="released",
                to="players.player",
            ),
        ),
        migrations.AlterField(
            model_name="transactionmovelog",
            name="signed",
            field=models.ForeignKey(
                help_text="The player being signed.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signed",
                to="players.player",
            ),
        ),
        migrations.AlterField(
            model_name="transactionmovelog",
            name="team",
            field=models.ForeignKey(
                help_text="The team making the transaction.",
                on_delete=django.db.models.deletion.CASCADE,
                to="teams.team",
            ),
        ),
    ]
