# Generated by Django 5.0.3 on 2024-07-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0026_alter_transactionmovelog_approved_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractlog",
            name="incentives",
            field=models.CharField(default="None", max_length=255),
        ),
        migrations.AlterField(
            model_name="contractlog",
            name="weeks_paid",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="paymentlog",
            name="week",
            field=models.IntegerField(default=16),
        ),
        migrations.AlterField(
            model_name="upgradelog",
            name="week",
            field=models.IntegerField(default=16),
        ),
    ]
