# Generated by Django 5.0.3 on 2024-07-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0027_alter_contractlog_incentives_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentlog",
            name="week",
            field=models.IntegerField(default=17),
        ),
        migrations.AlterField(
            model_name="upgradelog",
            name="week",
            field=models.IntegerField(default=17),
        ),
    ]
