# Generated by Django 5.0.3 on 2024-08-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0029_alter_paymentlog_week_alter_upgradelog_week"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contractlog",
            old_name="current_year_payment",
            new_name="year_1_payment",
        ),
        migrations.RenameField(
            model_name="contractlog",
            old_name="biennium_year_payment",
            new_name="year_2_payment",
        ),
        migrations.RenameField(
            model_name="contractlog",
            old_name="subsequent_year_payment",
            new_name="year_3_payment",
        ),
        migrations.AddField(
            model_name="contractlog",
            name="current_year",
            field=models.CharField(
                choices=[
                    ("Year 1", "Year 1"),
                    ("Year 2", "Year 2"),
                    ("Year 3", "Year 3"),
                ],
                default="1",
                max_length=32,
            ),
        ),
    ]
