# Generated by Django 5.0.3 on 2024-10-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0037_alter_paymentlog_season_alter_paymentlog_week_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentlog",
            name="week",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="upgradelog",
            name="week",
            field=models.IntegerField(default=5),
        ),
    ]
