# Generated by Django 5.0.3 on 2024-10-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0038_alter_paymentlog_week_alter_upgradelog_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='week',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='upgradelog',
            name='week',
            field=models.IntegerField(default=18),
        ),
    ]
