# Generated by Django 5.0.3 on 2024-11-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0039_alter_paymentlog_week_alter_upgradelog_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentlog",
            name="week",
            field=models.IntegerField(default=19),
        ),
        migrations.AlterField(
            model_name="upgradelog",
            name="week",
            field=models.IntegerField(default=19),
        ),
    ]
