# Generated by Django 5.0.3 on 2024-12-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0040_alter_paymentlog_week_alter_upgradelog_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='season',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='week',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='upgradelog',
            name='season',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='upgradelog',
            name='week',
            field=models.IntegerField(default=2),
        ),
    ]
