# Generated by Django 5.0.3 on 2025-02-11 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0042_alter_paymentlog_week_alter_upgradelog_week'),
        ('players', '0042_alter_player_user'),
        ('stats', '0050_remove_teamseasonstats_average_biggest_lead_and_more'),
        ('teams', '0008_remove_teamlogs_initiators_remove_teamlogs_playtypes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='season',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='week',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='upgradelog',
            name='season',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='upgradelog',
            name='week',
            field=models.IntegerField(default=18),
        ),
        migrations.CreateModel(
            name='ContractOfferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projected_role', models.CharField(choices=[('Regular', 'Regular'), ('Stash', 'Stash'), ('First Option', 'First Option'), ('Second Option', 'Second Option'), ('Third Option', 'Third Option'), ('Primary Scorer', 'Primary Scorer'), ('Primary Playmaker', 'Primary Playmaker'), ('On-Ball Defender', 'On-Ball Defender')], default='Regular', max_length=32)),
                ('length', models.IntegerField()),
                ('option', models.CharField(default='None', max_length=32)),
                ('year_1_payment', models.IntegerField()),
                ('year_2_payment', models.IntegerField(default=0)),
                ('year_3_payment', models.IntegerField(default=0)),
                ('no_trade_clause', models.BooleanField(default=False)),
                ('no_release_clause', models.BooleanField(default=False)),
                ('verbally_agreed', models.BooleanField(default=False)),
                ('officially_signed', models.BooleanField(default=False)),
                ('notes', models.CharField(default='None', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
    ]
