# Generated by Django 5.0.3 on 2025-02-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0043_alter_paymentlog_season_alter_paymentlog_week_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractlog',
            old_name='option',
            new_name='year_2_option',
        ),
        migrations.RenameField(
            model_name='contractofferlog',
            old_name='option',
            new_name='year_2_option',
        ),
        migrations.AddField(
            model_name='contractlog',
            name='year_3_option',
            field=models.CharField(default='None', max_length=32),
        ),
        migrations.AddField(
            model_name='contractofferlog',
            name='year_3_option',
            field=models.CharField(default='None', max_length=32),
        ),
    ]
