# Generated by Django 5.0.3 on 2025-02-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0044_rename_option_contractlog_year_2_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractofferlog',
            name='confirmation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
