# Generated by Django 5.0.3 on 2025-02-28 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0045_contractofferlog_confirmation_time'),
        ('players', '0043_alter_player_sp_alter_player_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='season',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='week',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='upgradelog',
            name='season',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='upgradelog',
            name='week',
            field=models.IntegerField(default=8),
        ),
        migrations.CreateModel(
            name='TrophyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trophy', models.CharField(choices=[('FMVP', 'FMVP'), ('All-TRC 1ST', 'All-TRC 1ST'), ('MIP', 'MIP'), ('ASG', 'ASG'), ('MVP', 'MVP'), ('ROY', 'ROY'), ('All-TRC 2ND', 'All-TRC 2ND'), ('DPOY', 'DPOY'), ('All-TRC D', 'All-TRC D'), ('CHAMP', 'CHAMP')], max_length=32)),
                ('season', models.IntegerField()),
                ('week', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
        ),
    ]
