# Generated by Django 5.0.3 on 2025-03-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0046_alter_paymentlog_season_alter_paymentlog_week_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trophylog',
            name='week',
        ),
        migrations.AlterField(
            model_name='trophylog',
            name='trophy',
            field=models.CharField(choices=[('All-TRC 1ST', 'All-TRC 1ST'), ('All-TRC D', 'All-TRC D'), ('DPOY', 'DPOY'), ('ASG', 'ASG'), ('FMVP', 'FMVP'), ('MVP', 'MVP'), ('CHAMP', 'CHAMP'), ('ROY', 'ROY'), ('All-TRC 2ND', 'All-TRC 2ND'), ('MIP', 'MIP')], max_length=32),
        ),
    ]
