# Generated by Django 5.0.3 on 2025-03-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0047_remove_trophylog_week_alter_trophylog_trophy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='week',
            field=models.IntegerField(default=22),
        ),
        migrations.AlterField(
            model_name='trophylog',
            name='trophy',
            field=models.CharField(choices=[('MVP', 'MVP'), ('All-TRC D', 'All-TRC D'), ('All-TRC 2ND', 'All-TRC 2ND'), ('ASG', 'ASG'), ('CHAMP', 'CHAMP'), ('All-TRC 1ST', 'All-TRC 1ST'), ('DPOY', 'DPOY'), ('FMVP', 'FMVP'), ('MIP', 'MIP'), ('ROY', 'ROY')], max_length=32),
        ),
        migrations.AlterField(
            model_name='upgradelog',
            name='week',
            field=models.IntegerField(default=22),
        ),
    ]
