# Generated by Django 5.0.3 on 2025-04-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0048_alter_paymentlog_week_alter_trophylog_trophy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trophylog',
            name='trophy',
            field=models.CharField(choices=[('All-TRC D', 'All-TRC D'), ('All-TRC 1ST', 'All-TRC 1ST'), ('MVP', 'MVP'), ('DPOY', 'DPOY'), ('ROY', 'ROY'), ('CHAMP', 'CHAMP'), ('FMVP', 'FMVP'), ('ASG', 'ASG'), ('All-TRC 2ND', 'All-TRC 2ND'), ('MIP', 'MIP')], max_length=32),
        ),
    ]
