# Generated by Django 5.0.3 on 2025-05-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0049_alter_trophylog_trophy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentlog",
            name="season",
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name="trophylog",
            name="trophy",
            field=models.CharField(
                choices=[
                    ("FMVP", "FMVP"),
                    ("All-TRC 2ND", "All-TRC 2ND"),
                    ("All-TRC 1ST", "All-TRC 1ST"),
                    ("MIP", "MIP"),
                    ("ASG", "ASG"),
                    ("CHAMP", "CHAMP"),
                    ("ROY", "ROY"),
                    ("MVP", "MVP"),
                    ("DPOY", "DPOY"),
                    ("All-TRC D", "All-TRC D"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="upgradelog",
            name="season",
            field=models.IntegerField(default=7),
        ),
    ]
