# Generated by Django 5.0.3 on 2025-05-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0051_alter_paymentlog_season_alter_paymentlog_week_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trophylog",
            name="trophy",
            field=models.CharField(
                choices=[
                    ("MIP", "MIP"),
                    ("CHAMP", "CHAMP"),
                    ("All-TRC 1ST", "All-TRC 1ST"),
                    ("MVP", "MVP"),
                    ("ROY", "ROY"),
                    ("All-TRC 2ND", "All-TRC 2ND"),
                    ("ASG", "ASG"),
                    ("FMVP", "FMVP"),
                    ("DPOY", "DPOY"),
                    ("All-TRC D", "All-TRC D"),
                ],
                max_length=32,
            ),
        ),
    ]
