# Generated by Django 5.0.3 on 2024-10-23 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0041_player_stashed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_amount', models.IntegerField(default=0, help_text='Amount in SP')),
                ('xp_amount', models.IntegerField(default=0, help_text='Amount in XP')),
                ('reason', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
        ),
    ]
