# Generated by Django 5.0.3 on 2024-06-19 02:14

import django.db.models.deletion
import simulation.scripts.default
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('color', models.CharField(default='#434648', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=16)),
                ('last_name', models.CharField(max_length=16)),
                ('position', models.CharField(choices=[('PG', 'PG'), ('SG', 'SG'), ('SF', 'SF'), ('PF', 'PF'), ('C', 'C')], max_length=2)),
                ('number', models.IntegerField()),
                ('height', models.IntegerField()),
                ('height_imperial', models.CharField(default='N/A', max_length=4)),
                ('weight', models.IntegerField()),
                ('wingspan', models.IntegerField()),
                ('jumpshot', models.CharField(default='N/A', max_length=32)),
                ('attributes', models.JSONField(default=simulation.scripts.default.default_attributes)),
                ('badges', models.JSONField(default=simulation.scripts.default.default_badges)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('retired', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.team')),
            ],
        ),
    ]
