# Generated by Django 5.0.3 on 2024-06-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_player_team_alter_player_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='sim_rating',
            field=models.IntegerField(default=0),
        ),
    ]
