# Generated by Django 5.0.3 on 2024-06-19 23:00

import simulation.scripts.default
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_player_sim_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='tendencies',
            field=models.JSONField(default=simulation.scripts.default.default_tendencies),
        ),
    ]
