# Generated by Django 5.0.3 on 2024-06-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_player_tendencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='wingspan',
            field=models.IntegerField(default=0),
        ),
    ]
