# Generated by Django 5.0.3 on 2024-06-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_alter_player_height_alter_player_wingspan'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='college',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='country',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
