# Generated by Django 5.0.3 on 2024-06-20 01:00

import simulation.scripts.default
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_alter_player_college_alter_player_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='tendencies',
            field=models.JSONField(blank=True, default=simulation.scripts.default.default_tendencies, null=True),
        ),
    ]
