# Generated by Django 5.0.3 on 2024-06-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_alter_player_college_alter_player_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.URLField(default='https://static.vecteezy.com/system/resources/previews/024/983/914/original/simple-user-default-icon-free-png.pngg'),
        ),
    ]
