# Generated by Django 5.0.3 on 2024-06-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_player_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.URLField(default='https://www.blythspartans.com/wp-content/uploads/2020/01/blank.png'),
        ),
    ]
