# Generated by Django 5.0.3 on 2024-06-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0015_alter_player_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='sp_spent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='xp_spent',
            field=models.IntegerField(default=0),
        ),
    ]
