# Generated by Django 5.0.3 on 2024-06-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0016_player_sp_spent_player_xp_spent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='image',
        ),
        migrations.AddField(
            model_name='player',
            name='svg_image',
            field=models.TextField(default=''),
        ),
    ]
