# Generated by Django 5.0.3 on 2024-06-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0017_remove_player_image_player_svg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='svg_image',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
