# Generated by Django 5.0.3 on 2024-06-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0019_player_jumpshot_blending_player_jumpshot_free_throw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='jumpshot_timing',
            field=models.CharField(default='N/A', max_length=32),
        ),
    ]
