# Generated by Django 5.0.3 on 2024-06-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0020_player_jumpshot_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='on_roster',
            field=models.BooleanField(default=False),
        ),
    ]
