# Generated by Django 5.0.3 on 2024-06-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0022_modification'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='modifications',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
