# Generated by Django 5.0.3 on 2024-06-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0024_remove_modification_active_modification_expires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modification',
            name='expires',
        ),
        migrations.AddField(
            model_name='modification',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
