# Generated by Django 5.0.3 on 2024-06-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0025_remove_modification_expires_modification_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modification',
            name='sp_price',
        ),
    ]
