# Generated by Django 5.0.3 on 2024-06-30 12:10

import simulation.scripts.default
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0026_remove_modification_sp_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='modifications',
            field=models.JSONField(blank=True, default=simulation.scripts.default.default_modifications, null=True),
        ),
    ]
