# Generated by Django 5.0.3 on 2024-07-05 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0015_remove_contractlog_player_contractlog_weeks_paid'),
        ('players', '0027_alter_player_modifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logs.contractlog'),
        ),
    ]
