# Generated by Django 5.0.3 on 2024-07-05 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0018_contractlog_player'),
        ('players', '0028_player_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='logs.contractlog'),
        ),
    ]
