# Generated by Django 5.0.3 on 2024-07-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0030_alter_player_jumpshot_alter_player_jumpshot_blending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='jumpshot',
            field=models.CharField(default='N/A', max_length=32),
        ),
        migrations.AlterField(
            model_name='player',
            name='jumpshot_blending',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='player',
            name='jumpshot_free_throw',
            field=models.CharField(default='N/A', max_length=32),
        ),
        migrations.AlterField(
            model_name='player',
            name='jumpshot_release_1',
            field=models.CharField(default='N/A', max_length=32),
        ),
        migrations.AlterField(
            model_name='player',
            name='jumpshot_release_2',
            field=models.CharField(default='N/A', max_length=32),
        ),
        migrations.AlterField(
            model_name='player',
            name='jumpshot_timing',
            field=models.CharField(default='N/A', max_length=32),
        ),
    ]
