# Generated by Django 5.0.3 on 2024-07-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "players",
            "0031_alter_player_jumpshot_alter_player_jumpshot_blending_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="coach_suggestion_attributes",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="player",
            name="coach_suggestion_badges",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="player",
            name="coach_suggestion_tendencies",
            field=models.JSONField(default=dict),
        ),
    ]
