# Generated by Django 5.0.3 on 2024-07-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0032_player_coach_suggestion_attributes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="coach_suggestion_attributes",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="coach_suggestion_badges",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="coach_suggestion_tendencies",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
