# Generated by Django 5.0.3 on 2024-08-07 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0035_alter_player_jumpshot_alter_player_jumpshot_blending_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modification',
            old_name='expired',
            new_name='multi_buy',
        ),
    ]
