# Generated by Django 5.0.3 on 2024-09-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0037_modification_xp_price_with_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="sp",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="xp",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="player",
            name="sp_spent",
            field=models.IntegerField(default=6000),
        ),
        migrations.AlterField(
            model_name="player",
            name="xp_spent",
            field=models.IntegerField(default=8500),
        ),
    ]
