# Generated by Django 5.0.3 on 2024-09-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0038_player_sp_player_xp_alter_player_sp_spent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="sp",
            field=models.IntegerField(default=6000),
        ),
        migrations.AlterField(
            model_name="player",
            name="sp_spent",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="player",
            name="xp",
            field=models.IntegerField(default=8500),
        ),
        migrations.AlterField(
            model_name="player",
            name="xp_spent",
            field=models.IntegerField(default=0),
        ),
    ]
