# Generated by Django 5.0.3 on 2024-10-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0039_alter_player_sp_alter_player_sp_spent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="rookie",
            field=models.BooleanField(default=False),
        ),
    ]
