# Generated by Django 5.0.3 on 2024-10-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0040_player_rookie"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="stashed",
            field=models.BooleanField(default=False),
        ),
    ]
