# Generated by Django 5.0.3 on 2025-02-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0042_alter_player_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='sp',
            field=models.IntegerField(default=7500),
        ),
        migrations.AlterField(
            model_name='player',
            name='xp',
            field=models.IntegerField(default=9500),
        ),
    ]
