# Generated by Django 5.0.3 on 2025-03-28 20:58

import simulation.scripts.default
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0043_alter_player_sp_alter_player_xp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='coach_suggestion_attributes',
        ),
        migrations.RemoveField(
            model_name='player',
            name='coach_suggestion_badges',
        ),
        migrations.RemoveField(
            model_name='player',
            name='coach_suggestion_tendencies',
        ),
        migrations.AddField(
            model_name='player',
            name='gear',
            field=models.JSONField(blank=True, default=simulation.scripts.default.default_gear, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='hotzones',
            field=models.JSONField(blank=True, default=simulation.scripts.default.default_hotzones, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='signatures',
            field=models.JSONField(blank=True, default=simulation.scripts.default.default_animations, null=True),
        ),
    ]
