# Generated by Django 5.0.3 on 2025-04-09 16:26

import simulation.scripts.default
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0044_remove_player_coach_suggestion_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='accessories',
            field=models.JSONField(blank=True, default=simulation.scripts.default.default_accessories, null=True),
        ),
    ]
