# Generated by Django 5.0.3 on 2025-05-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0045_player_accessories"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="girlfriend",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
