# Generated by Django 5.0.3 on 2025-05-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0046_player_girlfriend"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="presents_received",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
